### ISSUE TITLE
[S] Secondary (pills) navigation bar

### ISSUE THREAD

**Issue by tkeburia** [redbadger/esma-website#54]
AC:
 * All stages, and content within stages are separate pages
 * The highlighted pill should indicate the current page
 * Next/Previous CTAs at the bottom of the page
 * Desktop + Tablet + Mobile

**Comment by ramsayalbazzaz** [comment]
If this ticket is specifically just for the pills and slider then looks good. However noticed a few issues on the content below it, but not sure if that's being sorted with ticket #42 

- Padding on edges and top of content looks too much on mobile
-Seem to be missing the old breadcrumb design
-I haven't been able to test the school years, further education etc navigation. I assume this will be populated when we populate the content for these pages

@tkeburia @rjkerrison @cameronramsay @carinapope13
