### ISSUE TITLE
[S] Move chronology tiles to a Research page

### ISSUE THREAD

**Issue by tkeburia** [redbadger/esma-website#56]
AC:
 * Clicking on the chronology (timeline) item will scroll to the corresponding tile and highlight it (hover effect)
 * clicking on a tile will take the user to the life stage page and "Research" will not be highlighted in the nav bar anymore

**Comment by ramsayalbazzaz** [comment]
- The nodes on the timeline when clicked should take the user to the page, not scroll down
-Spacing between the timeline and body copy is a bit too much vs Zeplin designs on Tablet breakpoint
-"Home" breadcrumb link should navigate back to homepage. Same with all breadcrumbs.

Rest looks great!

@tkeburia @rjkerrison @sjltaylor @carinapope13 @cameronramsay
