### ISSUE TITLE
[M] Operational Review page

### ISSUE THREAD

**Issue by ramsayalbazzaz** [redbadger/esma-website#68]
'Supported By' now included on this page

Esma panel list: 
https://docs.google.com/document/d/1wJ6wUcdA05Ebzh63wVwWIiF-341nl2rs1AqHy06SS-k/edit?usp=sharing

**Comment by ramsayalbazzaz** [comment]
Page looks good in general. Few points:

- The text looks a bit far from the bullet points throughout the page versus Carina's design
-Text on the ESMA panel section is a bit tight, especially near the newsletter. Can we add some more space between the text and the newsletter
-Noticed also that the CTA is too close to the form field on the newsletter when looking at the iPad breakpoint

@tkeburia @rjkerrison @carinapope13 @cameronramsay

**Comment by carinapope13** [comment]
A few more comments in addition to Ramsay's:

- The spacing between the ESMA panel body copy "The energy and interest..." and the section below looks too tight, this should be 36px
- The spacing between the ESMA panel list of people and the copy below "Authored by Dr.Catherine..." is too tight, this should be 72px 
- Also, the fade in/out hover states on the buttons in the ESMA panel section is too long, can we speed this up

@rjkerrison @tkeburia

**Comment by rjkerrison** [comment]
@carinapope13 @ramsayalbazzaz These comments were addressed in #93 and are fixed at https://esma.community/operational-review now.
