### ISSUE TITLE
[S] Populate content (working life)

### ISSUE THREAD

**Issue by cameronramsay** [redbadger/esma-website#73]
- [x] populate copy into MDX files for each page
- [x] set up config required for ResearchNavigation (i.e. pills) to work

**Comment by ramsayalbazzaz** [comment]
- Spacing between the graphs is a bit too much on mobile

@carinapope13 @tkeburia

**Comment by carinapope13** [comment]
spacing between paragraphs + graphs on mobile is 36px (72 on tablet/desktop)
