### ISSUE TITLE
[S] Populate content (higher education)

### ISSUE THREAD

**Issue by cameronramsay** [redbadger/esma-website#74]
- [ ] populate copy into MDX files for each page
- [ ] set up config required for ResearchNavigation (i.e. pills) to work

**Comment by ramsayalbazzaz** [comment]
- There is quite a bit of spacing between the graphs on mobile
-Would it possible for the slider to show which section your in on mobile. So when I am on higher education its highlighted but hidden, I have to swipe to see it

@carinapope13 @tkeburia @cameronramsay @sjltaylor @rjkerrison
