### ISSUE TITLE
[S] Populate content (further education)

### ISSUE THREAD

**Issue by cameronramsay** [redbadger/esma-website#75]
- [ ] populate copy into MDX files for each page
- [ ] set up config required for ResearchNavigation (i.e. pills) to work

**Comment by ramsayalbazzaz** [comment]
- "Overview" in the breadcrumbs should be "Life stage overview"
-The back button is missing on the 'Life stage overview'. There is a button to go back to the previous life stage on all 'life stage overview' pages
-Space between next up button and footnotes is a bit too large on life stage overview page
-Graph missing on 'Post-16 educational trajectories' page
-Space between the breadcrumbs, contents, and title is a bit tight on mobile. Same on al research pages
-Spacing between some paragraphs bit large as well.

Some comments above. @carinapope13 Did you have any others?

@cameronramsay @tkeburia
