### ISSUE TITLE
Repositioning of pills Navigation bar

### ISSUE THREAD

**Issue by cameronramsay** [redbadger/esma-website#80]

**Comment by ramsayalbazzaz** [comment]
Early Years:
- In the breadcrumbs, "Overview" should say "Life stage overview" 
-In the pills and breadcrumbs, "Early Years Provision" should say "Educational provision"
-Spacing between breadcrumbs, contents drop-down, title and content is a bit tight on mobile. See image

![Image from iOS (32)](https://user-images.githubusercontent.com/69639162/92459985-4a8ca400-f1bf-11ea-8ea9-f23720ba39c5.png)

@tkeburia @cameronramsay @carinapope13 @rjkerrison @sjltaylor
